

database:
driverClass: org.postgresql.Driver
  user: ${DB_USER:-postgres}
  password: ${DB_PASSWORD:-postgres}
  url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/publisher-db

logging:
  level: INFO
  loggers:
    br.com.soeirosantos.publisher: DEBUG
    org.hibernate.SQL:
      level: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY:-changeme}
    secretKey: ${AWS_SECRET_KEY:-changeme}
  s3:
    bucketName: ${AWS_BUCKET_NAME:-changeme}
  sns:
    topicName: ${AWS_TOPIC_NAME:-changeme}

maxRequestSize: 52428800 #50MB
